// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PriceCompareData.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("12196b1a-d236-452b-b52b-4298c2ae5021"), entityTypeCount: 13)
        {
        }

        partial void Initialize()
        {
            var category = CategoryEntityType.Create(this);
            var categoryKeyword = CategoryKeywordEntityType.Create(this);
            var matchJob = MatchJobEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var productMatch = ProductMatchEntityType.Create(this);
            var priceHistory = PriceHistoryEntityType.Create(this);
            var jobDefinition = JobDefinitionEntityType.Create(this);
            var jobRun = JobRunEntityType.Create(this);
            var receipt = ReceiptEntityType.Create(this);
            var favoriteItem = FavoriteItemEntityType.Create(this);
            var favoritePriceAlert = FavoritePriceAlertEntityType.Create(this);
            var receiptItem = ReceiptItemEntityType.Create(this);
            var user = UserEntityType.Create(this);

            CategoryKeywordEntityType.CreateForeignKey1(categoryKeyword, category);
            ProductEntityType.CreateForeignKey1(product, category);
            FavoritePriceAlertEntityType.CreateForeignKey1(favoritePriceAlert, favoriteItem);
            ReceiptItemEntityType.CreateForeignKey1(receiptItem, receipt);

            CategoryEntityType.CreateAnnotations(category);
            CategoryKeywordEntityType.CreateAnnotations(categoryKeyword);
            MatchJobEntityType.CreateAnnotations(matchJob);
            ProductEntityType.CreateAnnotations(product);
            ProductMatchEntityType.CreateAnnotations(productMatch);
            PriceHistoryEntityType.CreateAnnotations(priceHistory);
            JobDefinitionEntityType.CreateAnnotations(jobDefinition);
            JobRunEntityType.CreateAnnotations(jobRun);
            ReceiptEntityType.CreateAnnotations(receipt);
            FavoriteItemEntityType.CreateAnnotations(favoriteItem);
            FavoritePriceAlertEntityType.CreateAnnotations(favoritePriceAlert);
            ReceiptItemEntityType.CreateAnnotations(receiptItem);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
