// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceCompareData.Data;

#nullable disable

namespace PriceCompareData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PriceCompareData.Entities.Compare.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Milk"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Bread"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Eggs"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Apple"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Toothpaste"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Rice"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Pasta"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Shampoo"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Soap"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Cheese"
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Chicken"
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Beef"
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Fish"
                        },
                        new
                        {
                            CategoryId = 14,
                            Name = "Yogurt"
                        },
                        new
                        {
                            CategoryId = 15,
                            Name = "Coffee"
                        },
                        new
                        {
                            CategoryId = 16,
                            Name = "Tea"
                        },
                        new
                        {
                            CategoryId = 17,
                            Name = "Soft Drink"
                        },
                        new
                        {
                            CategoryId = 18,
                            Name = "Beer"
                        },
                        new
                        {
                            CategoryId = 19,
                            Name = "Wine"
                        },
                        new
                        {
                            CategoryId = 20,
                            Name = "Cereal"
                        });
                });

            modelBuilder.Entity("PriceCompareData.Entities.Compare.CategoryKeyword", b =>
                {
                    b.Property<int>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeywordId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("KeywordId");

                    b.ToTable("CategoryKeywords");

                    b.HasData(
                        new
                        {
                            KeywordId = 1,
                            CategoryId = 1,
                            Keyword = "milk",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 2,
                            CategoryId = 1,
                            Keyword = "full cream",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 3,
                            CategoryId = 1,
                            Keyword = "skim",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 4,
                            CategoryId = 1,
                            Keyword = "lactose free",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 10,
                            CategoryId = 2,
                            Keyword = "bread",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 11,
                            CategoryId = 2,
                            Keyword = "wholemeal",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 12,
                            CategoryId = 2,
                            Keyword = "sourdough",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 20,
                            CategoryId = 3,
                            Keyword = "egg",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 21,
                            CategoryId = 3,
                            Keyword = "free range",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 30,
                            CategoryId = 4,
                            Keyword = "apple",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 31,
                            CategoryId = 4,
                            Keyword = "fuji",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 32,
                            CategoryId = 4,
                            Keyword = "gala",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 40,
                            CategoryId = 5,
                            Keyword = "toothpaste",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 41,
                            CategoryId = 5,
                            Keyword = "whitening",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 42,
                            CategoryId = 5,
                            Keyword = "fluoride",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 50,
                            CategoryId = 6,
                            Keyword = "rice",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 51,
                            CategoryId = 6,
                            Keyword = "basmati",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 52,
                            CategoryId = 6,
                            Keyword = "jasmine",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 60,
                            CategoryId = 7,
                            Keyword = "pasta",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 61,
                            CategoryId = 7,
                            Keyword = "spaghetti",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 62,
                            CategoryId = 7,
                            Keyword = "penne",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 70,
                            CategoryId = 8,
                            Keyword = "shampoo",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 71,
                            CategoryId = 8,
                            Keyword = "anti-dandruff",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 80,
                            CategoryId = 9,
                            Keyword = "soap",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 81,
                            CategoryId = 9,
                            Keyword = "bar soap",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 90,
                            CategoryId = 10,
                            Keyword = "cheese",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 91,
                            CategoryId = 10,
                            Keyword = "cheddar",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 92,
                            CategoryId = 10,
                            Keyword = "mozzarella",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 100,
                            CategoryId = 11,
                            Keyword = "chicken",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 101,
                            CategoryId = 11,
                            Keyword = "breast fillet",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 102,
                            CategoryId = 11,
                            Keyword = "drumstick",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 110,
                            CategoryId = 12,
                            Keyword = "beef",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 111,
                            CategoryId = 12,
                            Keyword = "mince",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 112,
                            CategoryId = 12,
                            Keyword = "steak",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 120,
                            CategoryId = 13,
                            Keyword = "fish",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 121,
                            CategoryId = 13,
                            Keyword = "salmon",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 122,
                            CategoryId = 13,
                            Keyword = "tuna",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 130,
                            CategoryId = 14,
                            Keyword = "yogurt",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 131,
                            CategoryId = 14,
                            Keyword = "greek",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 140,
                            CategoryId = 15,
                            Keyword = "coffee",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 141,
                            CategoryId = 15,
                            Keyword = "instant",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 142,
                            CategoryId = 15,
                            Keyword = "espresso",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 150,
                            CategoryId = 16,
                            Keyword = "tea",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 151,
                            CategoryId = 16,
                            Keyword = "green tea",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 152,
                            CategoryId = 16,
                            Keyword = "black tea",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 160,
                            CategoryId = 17,
                            Keyword = "cola",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 161,
                            CategoryId = 17,
                            Keyword = "soft drink",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 162,
                            CategoryId = 17,
                            Keyword = "soda",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 170,
                            CategoryId = 18,
                            Keyword = "beer",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 171,
                            CategoryId = 18,
                            Keyword = "lager",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 172,
                            CategoryId = 18,
                            Keyword = "ale",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 180,
                            CategoryId = 19,
                            Keyword = "wine",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 181,
                            CategoryId = 19,
                            Keyword = "red wine",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 182,
                            CategoryId = 19,
                            Keyword = "white wine",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 190,
                            CategoryId = 20,
                            Keyword = "cereal",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 191,
                            CategoryId = 20,
                            Keyword = "cornflakes",
                            Weight = 1
                        },
                        new
                        {
                            KeywordId = 192,
                            CategoryId = 20,
                            Keyword = "muesli",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("PriceCompareData.Entities.Compare.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PackageQty")
                        .HasColumnType("int");

                    b.Property<int?>("ShopType")
                        .HasColumnType("int");

                    b.Property<string>("SizeUnit")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("SizeValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId");

                    b.HasIndex("ShopType", "Name");

                    b.HasIndex("ShopType", "SourceId");

                    b.HasIndex("CategoryId", "SizeUnit", "SizeValue");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PriceCompareData.Entities.History.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfferType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShopType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
