version = 0.1

[default.deploy.parameters]
stack_name = "price-compare"
resolve_s3 = true
s3_prefix = "price-compare"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DbConnectionString=\"__REPLACE_ME__\""
image_repositories = []

[dev.deploy.parameters]
stack_name = "price-compare-dev"
resolve_s3 = true
s3_prefix = "price-compare-dev"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev DbConnectionString=\"__REPLACE_ME__\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "price-compare-prod"
resolve_s3 = true
s3_prefix = "price-compare-prod"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod DbConnectionString=\"__REPLACE_ME__\""
image_repositories = []
