version = 0.1

[default.deploy.parameters]
stack_name = "price-compare"
resolve_s3 = true
s3_prefix = "price-compare"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DbConnectionString=\"Host=aws-1-ap-southeast-2.pooler.supabase.com;Port=5432;Database=postgres;User Id=postgres.awegqbemxepbfoxnvztn;Password=Fch36910213#;Ssl Mode=Require;Trust Server Certificate=true\""
image_repositories = []
