using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using PriceCompareCore.Config;
using PriceCompareWeb.Controllers.Models;

namespace PriceCompareWeb.Services
{
    public interface IScrapeImportSqlService
    {
        Task<ScrapeImportSqlResult> GenerateAsync(ScrapeImportSqlRequest request, CancellationToken ct = default);
    }

    public class ScrapeImportSqlService : IScrapeImportSqlService
    {
        private readonly ScrapeExportOptions _options;
        private readonly IHostEnvironment _env;
        private readonly ILogger<ScrapeImportSqlService> _logger;

        public ScrapeImportSqlService(
            IOptions<ScrapeExportOptions> options,
            IHostEnvironment env,
            ILogger<ScrapeImportSqlService> logger)
        {
            _options = options.Value;
            _env = env;
            _logger = logger;
        }

        public async Task<ScrapeImportSqlResult> GenerateAsync(ScrapeImportSqlRequest request, CancellationToken ct = default)
        {
            if (string.IsNullOrWhiteSpace(request.ExportDir))
            {
                throw new InvalidOperationException("ExportDir is required.");
            }

            var root = ResolveRoot();
            var exportDir = ResolveUnderRoot(root, request.ExportDir);

            if (!Directory.Exists(exportDir))
            {
                throw new InvalidOperationException($"Export directory not found: {exportDir}");
            }

            var outputPath = ResolveOutputPath(exportDir, request.OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

            var batchSize = request.BatchSize ?? _options.BatchSize;
            if (batchSize <= 0) batchSize = 500;
            if (batchSize > 5000) batchSize = 5000;

            var priceHistoryPath = Path.Combine(exportDir, "pricehistory.csv");
            var productPath = Path.Combine(exportDir, "product.csv");

            if (!File.Exists(priceHistoryPath) && !File.Exists(productPath))
            {
                throw new InvalidOperationException("No CSV files found in export directory.");
            }

            await using var stream = new FileStream(outputPath, FileMode.Create, FileAccess.Write, FileShare.Read);
            await using var writer = new StreamWriter(stream, new UTF8Encoding(false));

            await writer.WriteLineAsync($"-- Generated by ScrapeImportSqlService at {DateTime.UtcNow:O}");
            await writer.WriteLineAsync("BEGIN;");

            var priceHistoryRows = 0;
            if (File.Exists(priceHistoryPath))
            {
                priceHistoryRows = await WritePriceHistorySqlAsync(writer, priceHistoryPath, batchSize, ct);
            }

            var productRows = 0;
            if (File.Exists(productPath))
            {
                productRows = await WriteProductSqlAsync(writer, productPath, batchSize, ct);
            }

            if (priceHistoryRows > 0)
            {
                await writer.WriteLineAsync("-- reset pricehistory id sequence");
                await writer.WriteLineAsync("SELECT setval(");
                await writer.WriteLineAsync("  pg_get_serial_sequence('pricehistory','id'),");
                await writer.WriteLineAsync("  COALESCE((SELECT MAX(id) FROM pricehistory), 0) + 1,");
                await writer.WriteLineAsync("  false");
                await writer.WriteLineAsync(");");
                await writer.WriteLineAsync();
            }

            await writer.WriteLineAsync("COMMIT;");

            _logger.LogInformation("Generated SQL file at {Path}", outputPath);

            string? preview = null;
            if (request.IncludeSql)
            {
                preview = await ReadPreviewAsync(outputPath, 4000, ct);
            }

            return new ScrapeImportSqlResult(
                exportDir,
                outputPath,
                priceHistoryRows,
                productRows,
                preview);
        }

        private string ResolveRoot()
        {
            var root = string.IsNullOrWhiteSpace(_options.ExportDir) ? "exports" : _options.ExportDir;
            return Path.IsPathRooted(root)
                ? root
                : Path.Combine(_env.ContentRootPath, root);
        }

        private static string ResolveUnderRoot(string root, string requested)
        {
            var basePath = Path.GetFullPath(root);
            var target = Path.IsPathRooted(requested)
                ? Path.GetFullPath(requested)
                : Path.GetFullPath(Path.Combine(basePath, requested));

            if (!target.StartsWith(basePath, StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException("ExportDir must be under the configured export root.");
            }

            return target;
        }

        private static string ResolveOutputPath(string exportDir, string? outputPath)
        {
            if (string.IsNullOrWhiteSpace(outputPath))
            {
                return Path.Combine(exportDir, "import.sql");
            }

            var target = Path.IsPathRooted(outputPath)
                ? Path.GetFullPath(outputPath)
                : Path.GetFullPath(Path.Combine(exportDir, outputPath));

            var basePath = Path.GetFullPath(exportDir);
            if (!target.StartsWith(basePath, StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException("OutputPath must be under the export directory.");
            }

            return target;
        }

        private static async Task<int> WritePriceHistorySqlAsync(
            StreamWriter writer,
            string csvPath,
            int batchSize,
            CancellationToken ct)
        {
            await writer.WriteLineAsync("-- pricehistory");
            var total = 0;
            var batch = new List<PriceHistoryRow>(batchSize);

            await foreach (var row in CsvRecordReader.ReadAsync(csvPath, ct))
            {
                if (row.IsHeader)
                {
                    continue;
                }

                if (row.Values.Count == 0)
                {
                    continue;
                }

                if (row.Values.All(string.IsNullOrWhiteSpace))
                {
                    continue;
                }

                var parsed = PriceHistoryRow.FromCsv(row.Values, row.HeaderMap);
                batch.Add(parsed);
                total++;

                if (batch.Count >= batchSize)
                {
                    await WritePriceHistoryBatchAsync(writer, batch, ct);
                    batch.Clear();
                }
            }

            if (batch.Count > 0)
            {
                await WritePriceHistoryBatchAsync(writer, batch, ct);
            }

            return total;
        }

        private static async Task<int> WriteProductSqlAsync(
            StreamWriter writer,
            string csvPath,
            int batchSize,
            CancellationToken ct)
        {
            await writer.WriteLineAsync("-- product");
            var total = 0;
            var withSource = new List<ProductRow>(batchSize);
            var withoutSource = new List<ProductRow>(batchSize);

            await foreach (var row in CsvRecordReader.ReadAsync(csvPath, ct))
            {
                if (row.IsHeader)
                {
                    continue;
                }

                if (row.Values.Count == 0)
                {
                    continue;
                }

                if (row.Values.All(string.IsNullOrWhiteSpace))
                {
                    continue;
                }

                var parsed = ProductRow.FromCsv(row.Values, row.HeaderMap);
                total++;

                if (!HasUsableSourceId(parsed))
                {
                    parsed = parsed with { SourceId = null };
                    withoutSource.Add(parsed);
                    if (withoutSource.Count >= batchSize)
                    {
                        await WriteProductBatchWithoutSourceAsync(writer, withoutSource, ct);
                        withoutSource.Clear();
                    }
                }
                else
                {
                    withSource.Add(parsed);
                    if (withSource.Count >= batchSize)
                    {
                        await WriteProductBatchWithSourceAsync(writer, withSource, ct);
                        withSource.Clear();
                    }
                }
            }

            if (withSource.Count > 0)
            {
                await WriteProductBatchWithSourceAsync(writer, withSource, ct);
            }

            if (withoutSource.Count > 0)
            {
                await WriteProductBatchWithoutSourceAsync(writer, withoutSource, ct);
            }

            return total;
        }

        private static bool HasUsableSourceId(ProductRow row)
        {
            if (string.IsNullOrWhiteSpace(row.SourceId))
            {
                return false;
            }

            // Historical export bug could serialize missing WWS IDs as "0".
            return !string.Equals(row.SourceId.Trim(), "0", StringComparison.Ordinal);
        }

        private static async Task WritePriceHistoryBatchAsync(StreamWriter writer, IReadOnlyList<PriceHistoryRow> batch, CancellationToken ct)
        {
            await writer.WriteLineAsync("WITH v(name, currentprice, imageurl, scrapedat, offertype, shoptype, promotext) AS (");
            await writer.WriteLineAsync("  VALUES");

            for (var i = 0; i < batch.Count; i++)
            {
                var row = batch[i];
                var line = $"  ({Sql.Text(row.Name, false)}, {Sql.Decimal(row.CurrentPrice)}, {Sql.Text(row.ImageUrl, false)}, {Sql.Timestamp(row.ScrapedAt)}, {Sql.Int(row.OfferType)}, {Sql.Int(row.ShopType)}, {Sql.Text(row.PromoText, true)})";
                line += i == batch.Count - 1 ? string.Empty : ",";
                await writer.WriteLineAsync(line);
            }

            await writer.WriteLineAsync(")");
            await writer.WriteLineAsync("UPDATE pricehistory ph");
            await writer.WriteLineAsync("SET currentprice = v.currentprice,");
            await writer.WriteLineAsync("    imageurl = v.imageurl,");
            await writer.WriteLineAsync("    scrapedat = v.scrapedat,");
            await writer.WriteLineAsync("    promotext = v.promotext");
            await writer.WriteLineAsync("FROM v");
            await writer.WriteLineAsync("WHERE ph.name = v.name");
            await writer.WriteLineAsync("  AND ph.shoptype IS NOT DISTINCT FROM v.shoptype");
            await writer.WriteLineAsync("  AND ph.offertype IS NOT DISTINCT FROM v.offertype");
            await writer.WriteLineAsync("  AND ph.scrapedat::date = v.scrapedat::date;");
            await writer.WriteLineAsync();
            await writer.WriteLineAsync("WITH v(name, currentprice, imageurl, scrapedat, offertype, shoptype, promotext) AS (");
            await writer.WriteLineAsync("  VALUES");

            for (var i = 0; i < batch.Count; i++)
            {
                var row = batch[i];
                var line = $"  ({Sql.Text(row.Name, false)}, {Sql.Decimal(row.CurrentPrice)}, {Sql.Text(row.ImageUrl, false)}, {Sql.Timestamp(row.ScrapedAt)}, {Sql.Int(row.OfferType)}, {Sql.Int(row.ShopType)}, {Sql.Text(row.PromoText, true)})";
                line += i == batch.Count - 1 ? string.Empty : ",";
                await writer.WriteLineAsync(line);
            }

            await writer.WriteLineAsync(")");
            await writer.WriteLineAsync("INSERT INTO pricehistory (name, currentprice, imageurl, scrapedat, offertype, shoptype, promotext)");
            await writer.WriteLineAsync("SELECT v.name, v.currentprice, v.imageurl, v.scrapedat, v.offertype, v.shoptype, v.promotext");
            await writer.WriteLineAsync("FROM v");
            await writer.WriteLineAsync("WHERE NOT EXISTS (");
            await writer.WriteLineAsync("  SELECT 1 FROM pricehistory ph");
            await writer.WriteLineAsync("  WHERE ph.name = v.name");
            await writer.WriteLineAsync("    AND ph.shoptype IS NOT DISTINCT FROM v.shoptype");
            await writer.WriteLineAsync("    AND ph.offertype IS NOT DISTINCT FROM v.offertype");
            await writer.WriteLineAsync("    AND ph.scrapedat::date = v.scrapedat::date");
            await writer.WriteLineAsync(");");
            await writer.WriteLineAsync();
        }

        private static async Task WriteProductBatchWithSourceAsync(StreamWriter writer, IReadOnlyList<ProductRow> batch, CancellationToken ct)
        {
            await writer.WriteLineAsync("UPDATE product p SET");
            await writer.WriteLineAsync("  name = d.name,");
            await writer.WriteLineAsync("  brand = COALESCE(d.brand, p.brand),");
            await writer.WriteLineAsync("  sizevalue = COALESCE(d.sizevalue, p.sizevalue),");
            await writer.WriteLineAsync("  sizeunit = COALESCE(d.sizeunit, p.sizeunit),");
            await writer.WriteLineAsync("  packageqty = COALESCE(d.packageqty, p.packageqty),");
            await writer.WriteLineAsync("  categoryid = COALESCE(d.categoryid, p.categoryid),");
            await writer.WriteLineAsync("  imageurl = COALESCE(d.imageurl, p.imageurl),");
            await writer.WriteLineAsync("  normalizedname = d.normalizedname,");
            await writer.WriteLineAsync("  normalizedbrand = d.normalizedbrand,");
            await writer.WriteLineAsync("  sizestandardvalue = d.sizestandardvalue,");
            await writer.WriteLineAsync("  sizestandardunit = d.sizestandardunit,");
            await writer.WriteLineAsync("  sizeunknown = d.sizeunknown,");
            await writer.WriteLineAsync("  brandunknown = d.brandunknown,");
            await writer.WriteLineAsync("  categoryunknown = d.categoryunknown,");
            await writer.WriteLineAsync("  lastseenat = GREATEST(p.lastseenat, d.lastseenat)");
            await writer.WriteLineAsync("FROM (");
            await writer.WriteLineAsync("  SELECT DISTINCT ON (v.shoptype, v.sourceid)");
            await writer.WriteLineAsync("    v.shoptype, v.sourceid, v.name, v.brand, v.sizevalue, v.sizeunit, v.packageqty, v.categoryid, v.imageurl, v.lastseenat,");
            await writer.WriteLineAsync("    v.normalizedname, v.normalizedbrand, v.sizestandardvalue, v.sizestandardunit,");
            await writer.WriteLineAsync("    v.sizeunknown, v.brandunknown, v.categoryunknown");
            await writer.WriteLineAsync("  FROM (VALUES");

            for (var i = 0; i < batch.Count; i++)
            {
                var row = batch[i];
                var line = $"  ({Sql.Int(row.ShopType)}::int, {Sql.Text(row.SourceId, false)}, {Sql.Text(row.Name, false)}, {Sql.Text(row.Brand, true)}, {Sql.Decimal(row.SizeValue)}::numeric, {Sql.Text(row.SizeUnit, true)}, {Sql.Int(row.PackageQty)}::int, {Sql.Int(row.CategoryId)}::int, {Sql.Text(row.ImageUrl, true)}, {Sql.Timestamp(row.LastSeenAt)}, {Sql.Text(row.NormalizedName, true)}, {Sql.Text(row.NormalizedBrand, true)}, {Sql.Decimal(row.SizeStandardValue)}::numeric, {Sql.Text(row.SizeStandardUnit, true)}, {Sql.Bool(row.SizeUnknown)}, {Sql.Bool(row.BrandUnknown)}, {Sql.Bool(row.CategoryUnknown)})";
                line += i == batch.Count - 1 ? string.Empty : ",";
                await writer.WriteLineAsync(line);
            }

            await writer.WriteLineAsync("  ) AS v(shoptype, sourceid, name, brand, sizevalue, sizeunit, packageqty, categoryid, imageurl, lastseenat, normalizedname, normalizedbrand, sizestandardvalue, sizestandardunit, sizeunknown, brandunknown, categoryunknown)");
            await writer.WriteLineAsync("  WHERE v.sourceid IS NOT NULL");
            await writer.WriteLineAsync("  ORDER BY v.shoptype, v.sourceid, v.lastseenat DESC, v.name DESC");
            await writer.WriteLineAsync(") AS d");
            await writer.WriteLineAsync("WHERE p.shoptype = d.shoptype");
            await writer.WriteLineAsync("  AND p.sourceid = d.sourceid;");
            await writer.WriteLineAsync();

            await writer.WriteLineAsync("INSERT INTO product (shoptype, sourceid, name, brand, sizevalue, sizeunit, packageqty, categoryid, imageurl, lastseenat, normalizedname, normalizedbrand, sizestandardvalue, sizestandardunit, sizeunknown, brandunknown, categoryunknown)");
            await writer.WriteLineAsync("SELECT d.shoptype, d.sourceid, d.name, d.brand, d.sizevalue, d.sizeunit, d.packageqty, d.categoryid, d.imageurl, d.lastseenat, d.normalizedname, d.normalizedbrand, d.sizestandardvalue, d.sizestandardunit, d.sizeunknown, d.brandunknown, d.categoryunknown");
            await writer.WriteLineAsync("FROM (");
            await writer.WriteLineAsync("  SELECT DISTINCT ON (v.shoptype, v.sourceid)");
            await writer.WriteLineAsync("    v.shoptype, v.sourceid, v.name, v.brand, v.sizevalue, v.sizeunit, v.packageqty, v.categoryid, v.imageurl, v.lastseenat,");
            await writer.WriteLineAsync("    v.normalizedname, v.normalizedbrand, v.sizestandardvalue, v.sizestandardunit,");
            await writer.WriteLineAsync("    v.sizeunknown, v.brandunknown, v.categoryunknown");
            await writer.WriteLineAsync("  FROM (VALUES");

            for (var i = 0; i < batch.Count; i++)
            {
                var row = batch[i];
                var line = $"  ({Sql.Int(row.ShopType)}::int, {Sql.Text(row.SourceId, false)}, {Sql.Text(row.Name, false)}, {Sql.Text(row.Brand, true)}, {Sql.Decimal(row.SizeValue)}::numeric, {Sql.Text(row.SizeUnit, true)}, {Sql.Int(row.PackageQty)}::int, {Sql.Int(row.CategoryId)}::int, {Sql.Text(row.ImageUrl, true)}, {Sql.Timestamp(row.LastSeenAt)}, {Sql.Text(row.NormalizedName, true)}, {Sql.Text(row.NormalizedBrand, true)}, {Sql.Decimal(row.SizeStandardValue)}::numeric, {Sql.Text(row.SizeStandardUnit, true)}, {Sql.Bool(row.SizeUnknown)}, {Sql.Bool(row.BrandUnknown)}, {Sql.Bool(row.CategoryUnknown)})";
                line += i == batch.Count - 1 ? string.Empty : ",";
                await writer.WriteLineAsync(line);
            }

            await writer.WriteLineAsync("  ) AS v(shoptype, sourceid, name, brand, sizevalue, sizeunit, packageqty, categoryid, imageurl, lastseenat, normalizedname, normalizedbrand, sizestandardvalue, sizestandardunit, sizeunknown, brandunknown, categoryunknown)");
            await writer.WriteLineAsync("  WHERE v.sourceid IS NOT NULL");
            await writer.WriteLineAsync("  ORDER BY v.shoptype, v.sourceid, v.lastseenat DESC, v.name DESC");
            await writer.WriteLineAsync(") AS d");
            await writer.WriteLineAsync("WHERE NOT EXISTS (");
            await writer.WriteLineAsync("  SELECT 1 FROM product p");
            await writer.WriteLineAsync("  WHERE p.shoptype = d.shoptype");
            await writer.WriteLineAsync("    AND p.sourceid = d.sourceid");
            await writer.WriteLineAsync(");");
            await writer.WriteLineAsync();
        }

        private static async Task WriteProductBatchWithoutSourceAsync(StreamWriter writer, IReadOnlyList<ProductRow> batch, CancellationToken ct)
        {
            await writer.WriteLineAsync("UPDATE product p SET");
            await writer.WriteLineAsync("  brand = COALESCE(v.brand, p.brand),");
            await writer.WriteLineAsync("  sizevalue = COALESCE(v.sizevalue, p.sizevalue),");
            await writer.WriteLineAsync("  sizeunit = COALESCE(v.sizeunit, p.sizeunit),");
            await writer.WriteLineAsync("  packageqty = COALESCE(v.packageqty, p.packageqty),");
            await writer.WriteLineAsync("  categoryid = COALESCE(v.categoryid, p.categoryid),");
            await writer.WriteLineAsync("  imageurl = COALESCE(v.imageurl, p.imageurl),");
            await writer.WriteLineAsync("  normalizedname = v.normalizedname,");
            await writer.WriteLineAsync("  normalizedbrand = v.normalizedbrand,");
            await writer.WriteLineAsync("  sizestandardvalue = v.sizestandardvalue,");
            await writer.WriteLineAsync("  sizestandardunit = v.sizestandardunit,");
            await writer.WriteLineAsync("  sizeunknown = v.sizeunknown,");
            await writer.WriteLineAsync("  brandunknown = v.brandunknown,");
            await writer.WriteLineAsync("  categoryunknown = v.categoryunknown,");
            await writer.WriteLineAsync("  lastseenat = GREATEST(p.lastseenat, v.lastseenat)");
            await writer.WriteLineAsync("FROM (VALUES");

            for (var i = 0; i < batch.Count; i++)
            {
                var row = batch[i];
                var line = $"  ({Sql.Int(row.ShopType)}::int, {Sql.Text(row.SourceId, true)}, {Sql.Text(row.Name, false)}, {Sql.Text(row.Brand, true)}, {Sql.Decimal(row.SizeValue)}::numeric, {Sql.Text(row.SizeUnit, true)}, {Sql.Int(row.PackageQty)}::int, {Sql.Int(row.CategoryId)}::int, {Sql.Text(row.ImageUrl, true)}, {Sql.Timestamp(row.LastSeenAt)}, {Sql.Text(row.NormalizedName, true)}, {Sql.Text(row.NormalizedBrand, true)}, {Sql.Decimal(row.SizeStandardValue)}::numeric, {Sql.Text(row.SizeStandardUnit, true)}, {Sql.Bool(row.SizeUnknown)}, {Sql.Bool(row.BrandUnknown)}, {Sql.Bool(row.CategoryUnknown)})";
                line += i == batch.Count - 1 ? string.Empty : ",";
                await writer.WriteLineAsync(line);
            }

            await writer.WriteLineAsync(") AS v(shoptype, sourceid, name, brand, sizevalue, sizeunit, packageqty, categoryid, imageurl, lastseenat, normalizedname, normalizedbrand, sizestandardvalue, sizestandardunit, sizeunknown, brandunknown, categoryunknown)");
            await writer.WriteLineAsync("WHERE v.sourceid IS NULL");
            await writer.WriteLineAsync("  AND p.shoptype = v.shoptype");
            await writer.WriteLineAsync("  AND p.name = v.name;");
            await writer.WriteLineAsync();

            await writer.WriteLineAsync("INSERT INTO product (shoptype, sourceid, name, brand, sizevalue, sizeunit, packageqty, categoryid, imageurl, lastseenat, normalizedname, normalizedbrand, sizestandardvalue, sizestandardunit, sizeunknown, brandunknown, categoryunknown)");
            await writer.WriteLineAsync("SELECT v.shoptype, v.sourceid, v.name, v.brand, v.sizevalue, v.sizeunit, v.packageqty, v.categoryid, v.imageurl, v.lastseenat, v.normalizedname, v.normalizedbrand, v.sizestandardvalue, v.sizestandardunit, v.sizeunknown, v.brandunknown, v.categoryunknown");
            await writer.WriteLineAsync("FROM (VALUES");

            for (var i = 0; i < batch.Count; i++)
            {
                var row = batch[i];
                var line = $"  ({Sql.Int(row.ShopType)}::int, {Sql.Text(row.SourceId, true)}, {Sql.Text(row.Name, false)}, {Sql.Text(row.Brand, true)}, {Sql.Decimal(row.SizeValue)}::numeric, {Sql.Text(row.SizeUnit, true)}, {Sql.Int(row.PackageQty)}::int, {Sql.Int(row.CategoryId)}::int, {Sql.Text(row.ImageUrl, true)}, {Sql.Timestamp(row.LastSeenAt)}, {Sql.Text(row.NormalizedName, true)}, {Sql.Text(row.NormalizedBrand, true)}, {Sql.Decimal(row.SizeStandardValue)}::numeric, {Sql.Text(row.SizeStandardUnit, true)}, {Sql.Bool(row.SizeUnknown)}, {Sql.Bool(row.BrandUnknown)}, {Sql.Bool(row.CategoryUnknown)})";
                line += i == batch.Count - 1 ? string.Empty : ",";
                await writer.WriteLineAsync(line);
            }

            await writer.WriteLineAsync(") AS v(shoptype, sourceid, name, brand, sizevalue, sizeunit, packageqty, categoryid, imageurl, lastseenat, normalizedname, normalizedbrand, sizestandardvalue, sizestandardunit, sizeunknown, brandunknown, categoryunknown)");
            await writer.WriteLineAsync("WHERE v.sourceid IS NULL");
            await writer.WriteLineAsync("  AND NOT EXISTS (");
            await writer.WriteLineAsync("    SELECT 1 FROM product p");
            await writer.WriteLineAsync("    WHERE p.shoptype = v.shoptype AND p.name = v.name");
            await writer.WriteLineAsync("  );");
            await writer.WriteLineAsync();
        }

        private static async Task<string> ReadPreviewAsync(string path, int maxChars, CancellationToken ct)
        {
            await using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true, leaveOpen: false);
            var buffer = new char[maxChars];
            var read = await reader.ReadAsync(buffer.AsMemory(0, maxChars), ct);
            return new string(buffer, 0, read);
        }

        private record PriceHistoryRow(
            string Name,
            decimal CurrentPrice,
            string ImageUrl,
            DateTime ScrapedAt,
            int? OfferType,
            int? ShopType,
            string? PromoText)
        {
            public static PriceHistoryRow FromCsv(IReadOnlyList<string> values, IReadOnlyDictionary<string, int> map)
            {
                string? promoText = null;
                if (map.TryGetValue("promotext", out var idx) && idx >= 0 && idx < values.Count)
                {
                    promoText = values[idx];
                }

                return new PriceHistoryRow(
                    Csv.Get(values, map, "name", required: true),
                    Csv.Decimal(values, map, "currentprice"),
                    Csv.Get(values, map, "imageurl", required: true),
                    Csv.Timestamp(values, map, "scrapedat"),
                    Csv.Int(values, map, "offertype"),
                    Csv.Int(values, map, "shoptype"),
                    string.IsNullOrWhiteSpace(promoText) ? null : promoText);
            }
        }

        private record ProductRow(
            int? ShopType,
            string? SourceId,
            string Name,
            string? Brand,
            decimal? SizeValue,
            string? SizeUnit,
            int? PackageQty,
            int? CategoryId,
            string? ImageUrl,
            DateTime LastSeenAt,
            string NormalizedName,
            string? NormalizedBrand,
            decimal? SizeStandardValue,
            string? SizeStandardUnit,
            bool SizeUnknown,
            bool BrandUnknown,
            bool CategoryUnknown)
        {
            public static ProductRow FromCsv(IReadOnlyList<string> values, IReadOnlyDictionary<string, int> map)
            {
                var normalizedBrand = Csv.Get(values, map, "normalizedbrand", required: false);
                if (string.IsNullOrWhiteSpace(normalizedBrand))
                {
                    normalizedBrand = null;
                }

                var sizeStandardUnit = Csv.Get(values, map, "sizestandardunit", required: false);
                if (string.IsNullOrWhiteSpace(sizeStandardUnit))
                {
                    sizeStandardUnit = null;
                }

                return new ProductRow(
                    Csv.Int(values, map, "shoptype"),
                    Csv.Get(values, map, "sourceid", required: false),
                    Csv.Get(values, map, "name", required: true),
                    Csv.Get(values, map, "brand", required: false),
                    Csv.DecimalNullable(values, map, "sizevalue"),
                    Csv.Get(values, map, "sizeunit", required: false),
                    Csv.Int(values, map, "packageqty"),
                    Csv.Int(values, map, "categoryid"),
                    Csv.Get(values, map, "imageurl", required: false),
                    Csv.Timestamp(values, map, "lastseenat"),
                    Csv.Get(values, map, "normalizedname", required: true),
                    normalizedBrand,
                    Csv.DecimalNullable(values, map, "sizestandardvalue"),
                    sizeStandardUnit,
                    Csv.Bool(values, map, "sizeunknown"),
                    Csv.Bool(values, map, "brandunknown"),
                    Csv.Bool(values, map, "categoryunknown"));
            }
        }

        private static class Sql
        {
            public static string Text(string? value, bool emptyAsNull)
            {
                if (string.IsNullOrEmpty(value))
                {
                    return emptyAsNull ? "NULL" : "''";
                }

                return $"'{value.Replace("'", "''")}'";
            }

            public static string Int(int? value)
                => value.HasValue ? value.Value.ToString(CultureInfo.InvariantCulture) : "NULL";

            public static string Decimal(decimal? value)
                => value.HasValue ? value.Value.ToString(CultureInfo.InvariantCulture) : "NULL";

            public static string Bool(bool? value)
            {
                if (!value.HasValue)
                {
                    return "NULL";
                }

                return value.Value ? "true" : "false";
            }

            public static string Timestamp(DateTime value)
                => $"'{value.ToUniversalTime():O}'::timestamptz";
        }

        private static class Csv
        {
            public static string Get(IReadOnlyList<string> values, IReadOnlyDictionary<string, int> map, string column, bool required)
            {
                if (!map.TryGetValue(column, out var idx))
                {
                    throw new InvalidOperationException($"Missing column '{column}'.");
                }

                if (idx < 0 || idx >= values.Count)
                {
                    return string.Empty;
                }

                var value = values[idx];
                if (required && string.IsNullOrWhiteSpace(value))
                {
                    throw new InvalidOperationException($"Column '{column}' is required.");
                }

                return value;
            }

            public static int? Int(IReadOnlyList<string> values, IReadOnlyDictionary<string, int> map, string column)
            {
                var raw = Get(values, map, column, required: false);
                if (string.IsNullOrWhiteSpace(raw))
                {
                    return null;
                }

                return int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out var parsed)
                    ? parsed
                    : null;
            }

            public static decimal Decimal(IReadOnlyList<string> values, IReadOnlyDictionary<string, int> map, string column)
            {
                var raw = Get(values, map, column, required: true);
                if (decimal.TryParse(raw, NumberStyles.Number, CultureInfo.InvariantCulture, out var parsed))
                {
                    return parsed;
                }

                throw new InvalidOperationException($"Invalid decimal in column '{column}'.");
            }

            public static decimal? DecimalNullable(IReadOnlyList<string> values, IReadOnlyDictionary<string, int> map, string column)
            {
                var raw = Get(values, map, column, required: false);
                if (string.IsNullOrWhiteSpace(raw))
                {
                    return null;
                }

                return decimal.TryParse(raw, NumberStyles.Number, CultureInfo.InvariantCulture, out var parsed)
                    ? parsed
                    : null;
            }

            public static DateTime Timestamp(IReadOnlyList<string> values, IReadOnlyDictionary<string, int> map, string column)
            {
                var raw = Get(values, map, column, required: true);
                if (DateTime.TryParse(raw, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal, out var parsed))
                {
                    return parsed;
                }

                throw new InvalidOperationException($"Invalid datetime in column '{column}'.");
            }

            public static bool Bool(IReadOnlyList<string> values, IReadOnlyDictionary<string, int> map, string column)
            {
                var raw = Get(values, map, column, required: true).Trim();
                if (bool.TryParse(raw, out var parsed))
                {
                    return parsed;
                }

                if (string.Equals(raw, "1", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }

                if (string.Equals(raw, "0", StringComparison.OrdinalIgnoreCase))
                {
                    return false;
                }

                throw new InvalidOperationException($"Invalid boolean in column '{column}'.");
            }
        }

        private readonly record struct CsvRow(bool IsHeader, IReadOnlyList<string> Values, IReadOnlyDictionary<string, int> HeaderMap);

        private static class CsvRecordReader
        {
            public static async IAsyncEnumerable<CsvRow> ReadAsync(string path, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct)
            {
                await using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);

                var headerMap = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
                var isHeader = true;

                foreach (var record in ReadRecords(reader))
                {
                    if (ct.IsCancellationRequested)
                    {
                        yield break;
                    }

                    if (isHeader)
                    {
                        for (var i = 0; i < record.Count; i++)
                        {
                            var key = record[i]?.Trim() ?? string.Empty;
                            if (!string.IsNullOrEmpty(key) && !headerMap.ContainsKey(key))
                            {
                                headerMap[key] = i;
                            }
                        }

                        yield return new CsvRow(true, record, headerMap);
                        isHeader = false;
                        continue;
                    }

                    yield return new CsvRow(false, record, headerMap);
                }
            }

            private static IEnumerable<IReadOnlyList<string>> ReadRecords(TextReader reader)
            {
                var record = new List<string>();
                var field = new StringBuilder();
                var inQuotes = false;

                while (true)
                {
                    var ch = reader.Read();
                    if (ch == -1)
                    {
                        if (inQuotes)
                        {
                            inQuotes = false;
                        }

                        if (field.Length > 0 || record.Count > 0)
                        {
                            record.Add(field.ToString());
                            yield return record;
                        }

                        yield break;
                    }

                    var c = (char)ch;

                    if (inQuotes)
                    {
                        if (c == '"')
                        {
                            var peek = reader.Peek();
                            if (peek == '"')
                            {
                                reader.Read();
                                field.Append('"');
                            }
                            else
                            {
                                inQuotes = false;
                            }
                        }
                        else
                        {
                            field.Append(c);
                        }

                        continue;
                    }

                    if (c == '"')
                    {
                        inQuotes = true;
                        continue;
                    }

                    if (c == ',')
                    {
                        record.Add(field.ToString());
                        field.Clear();
                        continue;
                    }

                    if (c == '\r' || c == '\n')
                    {
                        if (c == '\r' && reader.Peek() == '\n')
                        {
                            reader.Read();
                        }

                        record.Add(field.ToString());
                        field.Clear();
                        yield return record;
                        record = new List<string>();
                        continue;
                    }

                    field.Append(c);
                }
            }
        }
    }
}
