name: Jira Key Check

# trigger
on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - main
      - dev

jobs:
  jira-key-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # check whether the PR title contains Jira Key
      - name: Check PR title for Jira Key
        if: github.event_name == 'pull_request'
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          if [[ ! "${{ github.event.pull_request.title }}" =~ [A-Z]+-[0-9]+ ]]; then
            echo "❌ ERROR: PR title must include a Jira issue key (e.g. BTS-123)"
            exit 1
          fi

      # check whether the commit message contains Jira Key
      - name: Check commit messages for Jira Key
        if: github.event_name == 'push'
        run: |
          echo "Checking commit messages..."
          commits=$(git log --format=%B ${{ github.event.before }}..${{ github.sha }})
          echo "$commits"
          if ! echo "$commits" | grep -qE '[A-Z]+-[0-9]+'; then
            echo "❌ ERROR: Commit messages must include a Jira issue key (e.g. BTS-123)"
            exit 1
          fi
